name: Documentation Deployments

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.6
      - name: Install Dependencies
        run: bun i
      - name: Check Building & Linting
        run: bun prod && bun i && bun docs:prod
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
         folder: docs/out
         branch: docs
